services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
        bind:
            string $monsieurbizRicheditorDefaultElement: '%monsieurbiz.richeditor.config.default_element%'
            string $monsieurbizRicheditorDefaultElementDataField: '%monsieurbiz.richeditor.config.default_element_data_field%'
            Gaufrette\FilesystemInterface $filesystem: '@gaufrette.monsieurbiz_rich_editor_fixture_file_filesystem'
    
    MonsieurBiz\SyliusRichEditorPlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    MonsieurBiz\SyliusRichEditorPlugin\Fixture\:
        resource: '../../Fixture'

    MonsieurBiz\SyliusRichEditorPlugin\Twig\:
        resource: '../../Twig'

    MonsieurBiz\SyliusRichEditorPlugin\Uploader\:
        resource: '../../Uploader'

    monsieurbiz.richeditor.metadata_registry:
        class: MonsieurBiz\SyliusRichEditorPlugin\UiElement\Metadata\Registry

    MonsieurBiz\SyliusRichEditorPlugin\UiElement\Metadata\RegistryInterface: '@monsieurbiz.richeditor.metadata_registry'

    monsieurbiz.richeditor.registry:
        class: MonsieurBiz\SyliusRichEditorPlugin\UiElement\Registry

    MonsieurBiz\SyliusRichEditorPlugin\UiElement\RegistryInterface: '@monsieurbiz.richeditor.registry'

    # File uploader
    MonsieurBiz\SyliusRichEditorPlugin\Uploader\FileUploader:
        arguments:
            $fileTargetPath: '%monsieurbiz.richeditor.config.upload_directory%'
            $imageTargetPath: '%monsieurbiz.richeditor.config.image_upload_directory%'
            $publicDirectory: '%kernel.project_dir%/public'

    MonsieurBiz\SyliusRichEditorPlugin\Uploader\FileUploaderInterface: '@MonsieurBiz\SyliusRichEditorPlugin\Uploader\FileUploader'
